name: pipx

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build_pipx:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
        python: [3.6, 3.7, 3.8, 3.9,]
        exclude:
        - os: windows-2019
          python: 3.6
        - os: macos-11
          python: 3.6
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install pipx
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx --user
        python -m pipx ensurepath
    
    - name: Install openvino-dev
      run: |
        python -m pipx install openvino-dev
        python -m pipx --version

    - name: Test MO
      run: |
        mo -h
    - name: Run MO
      run: |
        mo --input_model files/models/segmentation.onnx

    - name: Check IR exists after MO
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "segmentation.xml, segmentation.bin"
        allow_failure: true

    - name: Run benchmark_app
      run: 
        benchmark_app -m segmentation.xml -t 3

    - name: Test POT
      run: | 
        pot -h

    - name: Run POT
      run: |
        pot -q default -m segmentation.xml -w segmentation.bin --engine simplified --data-source files/data --output-dir compressed --direct-dump --name segmentation_int8


